<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9f16d3b63bcef08ff243dc2d80db4693
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'DLXPlugins\\GBExtras\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DLXPlugins\\GBExtras\\' => 
        array (
            0 => __DIR__ . '/../..' . '/php',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9f16d3b63bcef08ff243dc2d80db4693::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9f16d3b63bcef08ff243dc2d80db4693::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit9f16d3b63bcef08ff243dc2d80db4693::$classMap;

        }, null, ClassLoader::class);
    }
}
