<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5ffc2044fb5721659a1089088baf7590
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'DLXPlugins\\GBHacks\\' => 19,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DLXPlugins\\GBHacks\\' => 
        array (
            0 => __DIR__ . '/../..' . '/php',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit5ffc2044fb5721659a1089088baf7590::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit5ffc2044fb5721659a1089088baf7590::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit5ffc2044fb5721659a1089088baf7590::$classMap;

        }, null, ClassLoader::class);
    }
}
