<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit48ace65096e2422bef3e34899f6e48c0
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'DLXPlugins\\AlertsDLX\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DLXPlugins\\AlertsDLX\\' => 
        array (
            0 => __DIR__ . '/../..' . '/php',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit48ace65096e2422bef3e34899f6e48c0::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit48ace65096e2422bef3e34899f6e48c0::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit48ace65096e2422bef3e34899f6e48c0::$classMap;

        }, null, ClassLoader::class);
    }
}
